const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY="rentalWalkthroughInspectionsV1";
let current=null,deferredPrompt=null;
const defaults=["Entry / Hall","Living Room","Kitchen","Primary Bedroom","Bedroom 2","Bathroom 1","Bathroom 2","Laundry","Exterior"];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random(),today=()=>new Date().toISOString().slice(0,10);
const all=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}},put=x=>localStorage.setItem(KEY,JSON.stringify(x));
function blank(){return{id:uid(),address:"",type:"Move-In",tenant:"",inspector:"",date:today(),overall:"Good",generalNotes:"",rooms:defaults.map(name=>({id:uid(),name,condition:"Good",clean:"Clean",working:"Yes",notes:"",photos:[]})),tenantSig:"",inspectorSig:"",updatedAt:Date.now()}}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function view(n){$("#homeView").classList.toggle("hidden",n!="home");$("#editorView").classList.toggle("hidden",n!="editor");$("#reportView").classList.toggle("hidden",n!="report");scrollTo(0,0)}
function home(){let a=all().sort((x,y)=>y.updatedAt-x.updatedAt);$("#inspectionList").innerHTML="";$("#emptyState").classList.toggle("hidden",!!a.length);a.forEach(it=>{let e=document.createElement("div");e.className="card saved-item";e.innerHTML='<div><h3>'+esc(it.address||"Untitled property")+'</h3><div class="saved-meta">'+esc(it.type)+" • "+esc(it.date||"No date")+"<br>"+esc(it.tenant||"No tenant listed")+'</div></div><div class="saved-actions"><button class="ghost open">Open</button><button class="ghost dup">Duplicate</button><button class="danger-link del">Delete</button></div>';e.querySelector(".open").onclick=()=>open(it.id);e.querySelector(".dup").onclick=()=>{let c=JSON.parse(JSON.stringify(it));c.id=uid();c.updatedAt=Date.now();c.address+=(c.address?" ":"")+"(Copy)";let x=all();x.push(c);put(x);home()};e.querySelector(".del").onclick=()=>{if(confirm("Delete this inspection?")){put(all().filter(x=>x.id!==it.id));home()}};$("#inspectionList").appendChild(e)})}
function open(id){current=all().find(x=>x.id===id);if(current){fill();view("editor")}}
function fill(){addressInput.value=current.address||"";typeInput.value=current.type||"Move-In";tenantInput.value=current.tenant||"";inspectorInput.value=current.inspector||"";dateInput.value=current.date||today();overallInput.value=current.overall||"Good";generalNotes.value=current.generalNotes||"";roomsContainer.innerHTML="";current.rooms.forEach(room);sigRestore(tenantSig,current.tenantSig);sigRestore(inspectorSig,current.inspectorSig)}
function room(r){let f=roomTemplate.content.cloneNode(true),c=f.querySelector(".room-card");c.dataset.id=r.id;f.querySelector(".room-name").value=r.name;f.querySelector(".room-condition").value=r.condition;f.querySelector(".room-clean").value=r.clean;f.querySelector(".room-working").value=r.working;f.querySelector(".room-notes").value=r.notes||"";let g=f.querySelector(".photo-grid");(r.photos||[]).forEach((src,i)=>g.appendChild(photo(src,r.id,i)));f.querySelector(".photo-input").onchange=async e=>{for(let file of e.target.files)r.photos.push(await compress(file));sync(false);fill()};f.querySelector(".remove-room").onclick=()=>{if(confirm("Remove "+r.name+"?")){current.rooms=current.rooms.filter(x=>x.id!==r.id);fill()}};roomsContainer.appendChild(f)}
function photo(src,id,i){let e=document.createElement("div");e.className="photo";e.innerHTML='<img alt="Inspection photo"><button title="Remove">×</button>';e.querySelector("img").src=src;e.querySelector("button").onclick=()=>{current.rooms.find(x=>x.id===id).photos.splice(i,1);fill()};return e}
function compress(file){return new Promise((ok,no)=>{let im=new Image;im.onload=()=>{let sc=Math.min(1,1280/im.width),c=document.createElement("canvas");c.width=Math.round(im.width*sc);c.height=Math.round(im.height*sc);c.getContext("2d").drawImage(im,0,0,c.width,c.height);ok(c.toDataURL("image/jpeg",.78))};im.onerror=no;im.src=URL.createObjectURL(file)})}
function sync(sigs=true){if(!current)return;current.address=addressInput.value.trim();current.type=typeInput.value;current.tenant=tenantInput.value.trim();current.inspector=inspectorInput.value.trim();current.date=dateInput.value;current.overall=overallInput.value;current.generalNotes=generalNotes.value.trim();$$(".room-card").forEach(c=>{let r=current.rooms.find(x=>x.id===c.dataset.id);if(r){r.name=c.querySelector(".room-name").value.trim()||"Room";r.condition=c.querySelector(".room-condition").value;r.clean=c.querySelector(".room-clean").value;r.working=c.querySelector(".room-working").value;r.notes=c.querySelector(".room-notes").value.trim()}});if(sigs){current.tenantSig=tenantSig.toDataURL();current.inspectorSig=inspectorSig.toDataURL()}current.updatedAt=Date.now()}
function save(){sync();let a=all(),i=a.findIndex(x=>x.id===current.id);i>=0?a[i]=current:a.push(current);try{put(a);toast("Saved")}catch{alert("This inspection is too large for browser storage. Export it, then remove some photos.")}}
function addRoom(){sync();current.rooms.push({id:uid(),name:"New Room",condition:"Good",clean:"Clean",working:"Yes",notes:"",photos:[]});fill()}
function sig(canvas){let c=canvas.getContext("2d"),d=false;c.lineWidth=3;c.lineCap="round";function p(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}canvas.onpointerdown=e=>{e.preventDefault();d=true;let q=p(e);c.beginPath();c.moveTo(q.x,q.y)};canvas.onpointermove=e=>{if(d){e.preventDefault();let q=p(e);c.lineTo(q.x,q.y);c.stroke()}};addEventListener("pointerup",()=>d=false)}
function sigRestore(c,d){let x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);if(d){let im=new Image;im.onload=()=>x.drawImage(im,0,0,c.width,c.height);im.src=d}}
function report(){sync();save();let rooms=current.rooms.map(r=>'<section class="report-room"><h2>'+esc(r.name)+'</h2><p><strong>Condition:</strong> '+esc(r.condition)+' &nbsp; <strong>Cleanliness:</strong> '+esc(r.clean)+' &nbsp; <strong>Working:</strong> '+esc(r.working)+'</p>'+(r.notes?'<p><strong>Notes:</strong> '+esc(r.notes).replace(/\n/g,"<br>")+"</p>":"")+(r.photos.length?'<div class="report-photos">'+r.photos.map(p=>'<img src="'+p+'" alt="Inspection photo">').join("")+"</div>":"<p><em>No photos added.</em></p>")+"</section>").join("");reportContent.innerHTML='<h1>Rental Inspection Report</h1><div class="sub">'+esc(current.address||"Untitled property")+'</div><div class="report-grid"><div><strong>Inspection type</strong><br>'+esc(current.type)+'</div><div><strong>Date</strong><br>'+esc(current.date)+'</div><div><strong>Tenant</strong><br>'+esc(current.tenant||"—")+'</div><div><strong>Inspector</strong><br>'+esc(current.inspector||"—")+'</div><div><strong>Overall condition</strong><br>'+esc(current.overall)+'</div></div>'+(current.generalNotes?'<p><strong>General notes:</strong><br>'+esc(current.generalNotes).replace(/\n/g,"<br>")+"</p>":"")+rooms+'<section class="report-signatures"><div><img src="'+current.tenantSig+'"><div class="label">Tenant signature</div></div><div><img src="'+current.inspectorSig+'"><div class="label">Inspector signature</div></div></section>';view("report")}
function loadZip(){return new Promise((ok,no)=>{if(window.JSZip)return ok();let s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js";s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
async function exportZip(){sync();save();try{await loadZip()}catch{return alert("Could not load the export tool. Check your internet connection.")}let z=new JSZip,p=z.folder("photos"),n=0,parts=[];current.rooms.forEach((r,ri)=>{let imgs=[];(r.photos||[]).forEach((src,pi)=>{let m=src.match(/^data:image\/(\w+);base64,(.*)$/);if(!m)return;let ext=m[1]=="jpeg"?"jpg":m[1],rn=(r.name||"room-"+(ri+1)).replace(/[^a-z0-9-_]+/gi,"-"),fn=String(++n).padStart(3,"0")+"-"+rn+"-"+(pi+1)+"."+ext;p.file(fn,m[2],{base64:true});imgs.push('<img src="photos/'+fn+'">')});parts.push("<section><h2>"+esc(r.name)+"</h2><p><b>Condition:</b> "+esc(r.condition)+" &nbsp; <b>Cleanliness:</b> "+esc(r.clean)+" &nbsp; <b>Working:</b> "+esc(r.working)+"</p>"+(r.notes?"<p><b>Notes:</b> "+esc(r.notes).replace(/\n/g,"<br>")+"</p>":"")+'<div class="photos">'+imgs.join("")+"</div></section>")});[["tenant-signature.png",current.tenantSig],["inspector-signature.png",current.inspectorSig]].forEach(x=>{let m=(x[1]||"").match(/^data:image\/png;base64,(.*)$/);if(m)z.file(x[0],m[1],{base64:true})});let h='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Rental Inspection Report</title><style>body{font-family:Arial;max-width:900px;margin:40px auto;padding:0 20px}section{margin:28px 0}.photos{display:grid;grid-template-columns:1fr 1fr;gap:10px}.photos img{width:100%}@media(max-width:650px){.photos{grid-template-columns:1fr}}</style><h1>Rental Inspection Report</h1><p>'+esc(current.address)+'</p><p><b>Type:</b> '+esc(current.type)+' &nbsp; <b>Date:</b> '+esc(current.date)+'<br><b>Tenant:</b> '+esc(current.tenant)+' &nbsp; <b>Inspector:</b> '+esc(current.inspector)+'<br><b>Overall:</b> '+esc(current.overall)+'</p>'+(current.generalNotes?"<p><b>General notes:</b><br>"+esc(current.generalNotes).replace(/\n/g,"<br>")+"</p>":"")+parts.join("");z.file("inspection-report.html",h);z.file("inspection-data.json",JSON.stringify(current,null,2));let b=await z.generateAsync({type:"blob"}),u=URL.createObjectURL(b),a=document.createElement("a"),safe=(current.address||"rental-inspection").replace(/[^a-z0-9-_]+/gi,"-");a.href=u;a.download=safe+"-"+(current.date||"inspection")+".zip";a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);toast("Exported report + "+n+" photos")}
function toast(t){let e=document.createElement("div");e.textContent=t;Object.assign(e.style,{position:"fixed",bottom:"24px",left:"50%",transform:"translateX(-50%)",background:"#111827",color:"#fff",padding:"10px 16px",borderRadius:"999px",zIndex:99,fontWeight:700});document.body.appendChild(e);setTimeout(()=>e.remove(),1400)}

document.addEventListener("gesturestart",e=>e.preventDefault(),{passive:false});
document.addEventListener("gesturechange",e=>e.preventDefault(),{passive:false});
document.addEventListener("gestureend",e=>e.preventDefault(),{passive:false});
let lastTouchEnd=0;
document.addEventListener("touchend",e=>{
  const now=Date.now();
  if(now-lastTouchEnd<=350)e.preventDefault();
  lastTouchEnd=now;
},{passive:false});

newInspectionBtn.onclick=()=>{current=blank();fill();view("editor")};backBtn.onclick=()=>{save();home();view("home")};saveBtn.onclick=save;saveBottomBtn.onclick=save;addRoomBtn.onclick=addRoom;reportBtn.onclick=report;reportBottomBtn.onclick=report;reportBackBtn.onclick=()=>view("editor");printBtn.onclick=()=>print();clearAllBtn.onclick=()=>{if(confirm("Delete every saved inspection on this device?")){localStorage.removeItem(KEY);home()}};$$("[data-clear-sig]").forEach(b=>b.onclick=()=>{let c=$("#"+b.dataset.clearSig);c.getContext("2d").clearRect(0,0,c.width,c.height)});
let ex=document.createElement("button");ex.className="ghost";ex.textContent="Export ZIP";ex.onclick=exportZip;reportBtn.parentNode.insertBefore(ex,reportBtn);
let ex2=document.createElement("button");ex2.className="ghost large";ex2.textContent="Export ZIP";ex2.onclick=exportZip;reportBottomBtn.parentNode.insertBefore(ex2,reportBottomBtn);
sig(tenantSig);sig(inspectorSig);home();
addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove("hidden")});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.classList.add("hidden")}};
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));